[tasks.start]
description = "starts all docker services"
run=[
    "docker compose -f ../../.config/docker-compose.yml up -d"
]

[tasks.stop]
description = "starts stop docker services"
run=[
    "docker compose -f ../../.config/docker-compose.yml down"
]
